apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 1
  template:
    metadata:
      name: todoapp
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: public.ecr.aws/j7f8d3t2/todoapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: todoapp

